### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [obijywk/rpresent#1]
I get the following when I try to compile with your instructions:

`pi@raspberrypi:~/Apps/openvg/build$ make
make[2]: ../src/window.cpp: Timestamp out of range; substituting 1969-12-31 19:00:00
make[2]: ../src/window.h: Timestamp out of range; substituting 1969-12-31 19:00:00
[ 20%] Built target window
make[2]: ../src/text.cpp: Timestamp out of range; substituting 1969-12-31 19:00:00
make[2]: ../src/text.h: Timestamp out of range; substituting 1969-12-31 19:00:00
[ 40%] Building CXX object src/CMakeFiles/text.dir/text.cpp.o
/home/pi/Apps/openvg/src/text.cpp: In member function ‘void rpresent::Text::DrawString(VGfloat, VGfloat, const std::string&)’:
/home/pi/Apps/openvg/src/text.cpp:159: error: expected initializer before ‘:’ token
/home/pi/Apps/openvg/src/text.cpp:164: error: expected ‘)’ before ‘;’ token
make[2]: *** [src/CMakeFiles/text.dir/text.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/text.dir/all] Error 2
make: *** [all] Error 2`

**Comment by obijywk** [comment]
Looks like your compiler doesn't like my C++11 style foreach loop. I suspected that was a silly thing to use :-P
What do you get when you run "gcc -v"? I get:

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-1.1+rpi2' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-float=hard --with-fpu=vfp --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-1.1+rpi2) 

As a quick fix you could replace that whole loop with this one instead:
for (int i = 0; i < str.length(); i++) {
  indices[i] = (VGuint)str.at(i);
}
